//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incidencias_Infor.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class hardware
    {
        public int incidencia { get; set; }
        public string num_serie { get; set; }
        public int tipo { get; set; }
        public Nullable<short> garantia { get; set; }
        public string modelo { get; set; }
        public int codigo { get; set; }
    
        public virtual incidencia incidencia1 { get; set; }
        public virtual tipohw tipohw { get; set; }
    }
}
