//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incidencias_Infor.Backend.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class incidenciasEntities : DbContext
    {
        public incidenciasEntities()
            : base("name=incidenciasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<articulo> articulo { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<hardware> hardware { get; set; }
        public virtual DbSet<incidencia> incidencia { get; set; }
        public virtual DbSet<lugar> lugar { get; set; }
        public virtual DbSet<permiso> permiso { get; set; }
        public virtual DbSet<profesor> profesor { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<software> software { get; set; }
        public virtual DbSet<tipohw> tipohw { get; set; }
    }
}
