//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incidencias_Infor.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class software
    {
        public int codigo { get; set; }
        public string version { get; set; }
        public int articulo { get; set; }
    
        public virtual articulo articulo1 { get; set; }
    }
}
